### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by tekuto1437** [Nxve/AutoMudae#13]
Idk why but script is not even running.
![image](https://user-images.githubusercontent.com/78407541/225284830-53c3e9f5-70db-4019-ab9d-b6e2360f7943.png)
I tried to use token too but outcome is the same. I would be glad if you help me.

**Comment by Nxve** [comment]
This project is discontinued. I'm currently remaking it as a [Chrome extension](https://github.com/Nxve/AutoMudaeExt).
