### ISSUE TITLE
problème récupération information  

### ISSUE THREAD

**Issue by didi932** [Nxve/AutoMudae#14]
bonjour je n'arrive pas a configuré le bot quand j'appuie sur RUN j'ai un message rouge qui apparait en me disant ( Impossible de récupérer les information pour l'utilisateur****** Assurez vous que votre configuration $tu expose toutes les information 
![okok](https://user-images.githubusercontent.com/129004685/228362602-dd068508-ed8a-41cf-9957-25eb05f8c5c1.png)

**Comment by Nxve** [comment]
Check [this](https://github.com/Nxve/AutoMudae/issues/13#issuecomment-1470878536).
