### ISSUE TITLE
Make sure $tu configuration exposes every information

### ISSUE THREAD

**Issue by Valkorion7** [Nxve/AutoMudae#3]
hello i have a problem with the script i do the command $ta claim rolls daily keys kakerareact kakerapower kakerainfo kakerastock rt dk rollsreset and click on run but it says couldn't retrieve needed informations for user .... Make sure $tu configuration exposes every information, what should i do ?

**Comment by 0mazar** [comment]
I'm having the same exact issue.

**Comment by KeenanPayne504** [comment]
Hello, I am having a similar issue also. I double checked and made sure My $tuarrange lists all possible information but am still experiencing this. Does it have to be in a specific order?

**Comment by Nxve** [comment]
Sorry about the late response.

I'll transfer the userscript to GreasyFork and fix some of these issues. If you keep getting this message after installing it from GreasyFork, feel free to reopen this issue.

**Comment by Valkorion7** [comment]
hello can i have the link
