### ISSUE TITLE
how does the bot claim cards

### ISSUE THREAD

**Issue by starss11** [Nxve/AutoMudae#6]
hello,

just wondering, do i input the characters i want it to claim in the interesting mentions section, and if so, in what format? 
like this?
Zero Two
Rem
Nezuko Kamado

does the bot only collect your wishlisted cards?

**Comment by Nxve** [comment]
For now, it claims characters wished by any of your accounts and/or wished by one of the nicknames that you put in "Interesting Mentions", separated by comma.

A list of interesting characters to claim even if not wished are planned to implemented.
