### ISSUE TITLE
same issue

### ISSUE THREAD

**Issue by Valkorion7** [Nxve/AutoMudae#8]
hello i'm in france and the but says make sure $tu configuration expose every information..... what should i do

**Comment by starss11** [comment]
use command $lang pt-br in mudae and then make sure you do $tuarrange with all of the possible values

**Comment by Valkorion7** [comment]
Im not admin but in a secondary serv it works thanks

**Comment by Nxve** [comment]
Sorry for the late response. I'm currently remaking it as a browser extension instead of userscript.
